### ISSUE TITLE
Internal-simulation

### ISSUE THREAD

**Issue by davekyle** [Presage/Presage2#42]
Handlers for allowing an agent to simulate it's surroundings. 
- Should be able to simulate "as itself" (ie, work out what the result will be of a given action)
- Should be able to simulate "as another" (ie, put itself in another agent's shoes and work out what it would do in that position)
- The internal simulations need to be able to collect data to return as a result (so that the best action can be chosen)
- Simulating partial environments (only the locality, not the entire environment necessarily) or the whole thing (maybe)
- Need to be able to specify a simplified agentmodel to use for the agents being simulated, because otherwise you end up simulating agents that are going to use simulations to make their decisions ...

**Comment by sammacbeth** [comment]
I think this is more just something you need to write an algorithm for rather than something I can provide an API for. You can create a simulation within the agent by just instantiating the required classes and analysing the state of them given the stimuli you want to test. I think you should be able to do all the points given with such an approach.
